# -*- coding: utf-8 -*-
"""model_definition.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15F9LfnlPmg3Of9PJ-9AjdovNzxGhGKk_
"""

"""
models/model_definition.py
---------------------------
Defines the custom ResNet18 model for surface defect classification.

Model used: ResNet18 (pretrained on ImageNet, fine-tuned)
Dataset: NEU Surface Defect Dataset
Classes: ['crazing', 'inclusion', 'patches', 'pitted_surface', 'rolled-in_scale', 'scratches']
"""

import torch
import torch.nn as nn
from torchvision import models


class DefectResNet18(nn.Module):
    """
    Custom ResNet18 model for defect detection.
    Reuses pretrained ImageNet weights and replaces the final layer
    to classify six defect categories.
    """

    def __init__(self, num_classes=6, pretrained=True):
        super(DefectResNet18, self).__init__()

        # Load pretrained ResNet18 model
        self.model = models.resnet18(
            weights=models.ResNet18_Weights.DEFAULT if pretrained else None
        )

        # Freeze base layers to keep pretrained features fixed
        for param in self.model.parameters():
            param.requires_grad = False

        # Replace the final layer to match the defect classes
        in_features = self.model.fc.in_features
        self.model.fc = nn.Sequential(
            nn.Linear(in_features, 256),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        return self.model(x)


def load_trained_model(weights_path, device=None):
    """
    Loads the fine-tuned ResNet18 model with saved weights (.pth file)
    Args:
        weights_path (str): Path to saved model weights
        device: 'cuda' or 'cpu'
    Returns:
        model (nn.Module): Model ready for inference
    """

    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model = DefectResNet18(num_classes=6, pretrained=False)
    model.load_state_dict(torch.load(weights_path, map_location=device))
    model.to(device)
    model.eval()
    return model


if __name__ == "__main__":
    # Quick test to verify model loads correctly
    print("🔍 Testing DefectResNet18 model definition...")
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = DefectResNet18(num_classes=6)
    model.to(device)

    dummy_input = torch.randn(1, 3, 224, 224).to(device)
    output = model(dummy_input)
    print(f"✅ Model test successful! Output shape: {output.shape}")

